Sep 04 10:02:52 hotel-management-server gunicorn[2703100]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/django/db/backends/utils.py", li>
Sep 04 10:02:52 hotel-management-server gunicorn[2703100]:     with self.db.wrap_database_errors:
Sep 04 10:02:52 hotel-management-server gunicorn[2703100]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in>
Sep 04 10:02:52 hotel-management-server gunicorn[2703100]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Sep 04 10:02:52 hotel-management-server gunicorn[2703100]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/django/db/backends/utils.py", li>
Sep 04 10:02:52 hotel-management-server gunicorn[2703100]:     return self.cursor.execute(sql, params)
Sep 04 10:02:52 hotel-management-server gunicorn[2703100]: django.db.utils.ProgrammingError: column staff_profile.full_name does not exist
Sep 04 10:02:52 hotel-management-server gunicorn[2703100]: LINE 1: ...rofile"."user_id", "staff_profile"."employee_id", "staff_pro...
Sep 04 10:02:52 hotel-management-server gunicorn[2703100]:                                                              ^
Sep 04 10:03:16 hotel-management-server gunicorn[2703098]: Internal Server Error: /api/users/staff/2/
