Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:     response = handler(request, *args, **kwargs)
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/rest_framework_simplejwt/views.p>
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:     serializer.is_valid(raise_exception=True)
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", >
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:     self._validated_data = self.run_validation(self.initial_data)
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", >
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:     value = self.validate(value)
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:   File "/home/ubuntu/hotel-management-backend/apps/users/serializers.py", line 16, in validate
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]:     data['first_name'] = self.user.first_name
Sep 04 08:19:53 hotel-management-server gunicorn[2700435]: AttributeError: 'CustomUser' object has no attribute 'first_name'
lines 1-23/23 (END)
